### ISSUE TITLE
pip3 install networkit failed with error code1

### ISSUE THREAD

**Issue by thomasbonnet** [networkit/networkit#393] opened 2019-07-30 15:58 UTC
Hello,
I'm trying to install networkit in a docker container for a while without any success.
Here are the versions of my libs:
- python 3.7.3
- pip 19.2.1
- g++ (Debian 6.3.0-18+deb9u1) 6.3.0
- cmake version 3.7.2
pip3 freeze gives the following:
```
backcall==0.1.0
cycler==0.10.0
decorator==4.4.0
ipython==7.7.0
ipython-genutils==0.2.0
jedi==0.14.1
kiwisolver==1.1.0
matplotlib==3.1.1
networkit==5.0
networkx==2.3
numpy==1.17.0
pandas==0.25.0
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
prompt-toolkit==2.0.9
ptyprocess==0.6.0
Pygments==2.4.2
pyparsing==2.4.1.1
python-dateutil==2.8.0
pytz==2019.1
scipy==1.3.0
six==1.12.0
tabulate==0.8.3
traitlets==4.3.2
wcwidth==0.1.7
```

The error  is the following :
```
    writing networkit.egg-info/PKG-INFO
    writing dependency_links to networkit.egg-info/dependency_links.txt
    writing requirements to networkit.egg-info/requires.txt
    writing top-level names to networkit.egg-info/top_level.txt
    reading manifest file 'networkit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'extlibs/tlx/.git'
    writing manifest file 'networkit.egg-info/SOURCES.txt'
    Copying networkit.egg-info to /usr/lib/python3.7/site-packages/networkit-5.0-py3.7.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-35pd80y2/networkit/setup.py", line 282, in <module>
        zip_safe                        = False) # see https://cython.readthedocs.io/en/latest/src/reference/compilation.html
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 564, in run
        outputs = self.get_outputs()
      File "/usr/lib/python3.7/distutils/command/install.py", line 606, in get_outputs
        for filename in cmd.get_outputs():
      File "/usr/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 117, in get_outputs
        outputs = orig.install_lib.get_outputs(self)
      File "/usr/lib/python3.7/distutils/command/install_lib.py", line 197, in get_outputs
        self.install_dir)
      File "/usr/lib/python3.7/distutils/command/install_lib.py", line 148, in _mutate_outputs
        build_files = build_cmd.get_outputs()
      File "/usr/lib/python3.7/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: get_outputs
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-35pd80y2/networkit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-35pd80y2/networkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kbodh4r8/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```
Any help would be greatly appreciated...

Regards, Thomas

**Comment by mikicz** [comment] 2019-08-01 12:13
I've got the same issue on my Fedora 30 machine.

Python 3.7.3
Pip 19.2.1
Setuptools 41.0.1
GCC 9.1.1
CMake 3.14.5

Steps to reproduce and outputs attached.
[networkit_log.txt](https://github.com/networkit/networkit/files/3456591/networkit_log.txt)

**Comment by avdgrinten** [comment] 2019-08-01 12:32
Thank you for the reports. I will look into this. It is quite strange that this error seems to happen in `setuptools` code (that we do not control). NetworKit customizes the `build_ext` step of setuptools quite heavily, but I do not see this step appearing in the stack trace.

**Comment by avdgrinten** [comment] 2019-08-01 12:38
Okay, distutils calls into `build_ext.get_outputs()` that NetworKit does not provide, via this code path:
https://github.com/python/cpython/blob/1a057bab0f18d6ad843ce321d1d77a4819497ae4/Lib/distutils/command/install_lib.py#L195

The fix is to provide a `get_outputs()` function similar to the one provided by distutils itself.
https://github.com/python/cpython/blob/master/Lib/distutils/command/build_ext.py#L429

**Comment by fabratu** [comment] 2019-08-01 16:27
@avdgrinten I will also take a look into it, since this is similar to errors when trying to pack networkit in pip-wrapper such as homebrew. What seems puzzling is that `get_outputs()` is not new in python and was not changed since 3.5. I can also (with the same package versions but not same distro) not recreate the problem from pip/pip3. The same error occurs only with homebrew calling pip. This has to be connected somehow to the way pip calls `setup.py`. I will try to modify the `build_ext` step to include a `get_outputs()` method and see if this helps.

.

**Comment by mikicz** [comment] 2019-08-01 19:48
I created a very simple Dockerfile with Fedora which reproduces the error. Hope it helps.

https://github.com/mikicz/networkit-393

**Comment by avdgrinten** [comment] 2019-08-02 11:01
Thank you for the Dockerfile, that is indeed helpful. I do not know what exactly caused this problem (probably a change in pip or setuptools) but we should have a fix in a few hours.

**Comment by thomasbonnet** [comment] 2019-08-02 14:28
Thanks to all of you for spending time on this issue. 
In my case, I should mention that although the install process is ending with an error, networkit is well installed and if I run pip install a second time, all is working correctly.
I hope it could help.
Cheers

**Comment by fabratu** [comment] 2019-08-02 14:49
@thomasbonnet  It doesn't end that well in all cases unfortunately. It makes sense however, that your installation (may) work despite the error, since it takes place near the end of the install stack. 

In addition this problem needs some more research. With the same package versions and same distros, the conda package manages to install fine in the first place.

**Comment by mikicz** [comment] 2019-08-02 14:58
> networkit is well installed and if I run pip install a second time, all is working correctly.

Have you tried running anything from it? That was the case for me (i could import networkit and another run of pip install said it is installed), but when I tried using something from it (I think extracting the largest connected component) I threw an error (unfortunately don't have it available right now)

**Comment by avdgrinten** [comment] 2019-08-05 06:51
The issue should now be fixed on the `Dev` (which also includes new features) and `release-5.0` (which tracks bugfixes compared to 5.0 only) branches. Could you verify that this fixes your issue? (Clone the repository, check out the `release-5.0` branch and install NetworKit using `pip3 install <path-to-repository>`.)

**Comment by mikicz** [comment] 2019-08-05 09:57
I was able to install without error from the release-5.0 branch.

**Comment by thomasbonnet** [comment] 2019-08-05 14:56
Hello,
I was also able to install without any errors from the release-5.0 and Dev branches.
Thank you avdgrinten.

**Comment by hmeyerhenke** [comment] 2019-08-05 15:07
Thank you very much to all who contributed to resolving this issue (which includes raising it).

**Comment by avdgrinten** [comment] 2019-08-05 15:15
We will probably do a bug fix release tomorrow to make the patch available to all people installing via pip.

**Comment by thomasbonnet** [comment] 2019-08-05 15:25
Yes, many thanks to all of you. Should I close the ticket now? or do you want me to wait until the fix is released?

**Comment by fabratu** [comment] 2019-08-05 15:35
I can confirm, that the patch works on Mac OS 10.11 and 10.13. The patch will be distributed to conda. This can take a few more days, since it first has to be approved externally.

**Comment by avdgrinten** [comment] 2019-08-06 07:23
@fabratu The PyPI package has been updated to 5.0.1

**Comment by fabratu** [comment] 2019-08-06 09:32
@avdgrinten Thx :) conda recipe is updated and merged, takes some time before available via forge channel. Guess we can close the issue now?

**Closed** 2019-08-12 08:31 UTC
