### ISSUE TITLE
Error in Assertion when attempting to a draw a multigraph with nit

### ISSUE THREAD

**Issue by Haaroon** [networkit/networkit#707] opened 2021-02-16 21:40 UTC
Version Networkit 8.0
Version Networkx 2.5

Example graph 
```
import networkit as nit
g = nit.Graph()
g.addNode()
g.addNode()
g.addEdge(0,1)
g.addEdge(0,1)
g.numberOfEdges() # 2
nit.viztasks.drawGraph(g) # Assertion Error
```
Possible solutions: 
Either drawGraph must implement multigraph conversion by default and detect if its a multigraph, 
or drawGraph should convert multigraph to graph or otherway round but with an explicit argument.

**Comment by hmeyerhenke** [comment] 2021-02-18 11:42
Thanks for your note. NetworKit does not always handle multigraphs properly. This was a design decision we took early on. Thus, multigraphs can lead to various sorts of unintended behavior. To remedy this on a global scale (and not only for the function you mention), we would need to change a lot. Currently, we do not have the resources for that.

But what should not happen is that a second addEdge() call leads to a multi-edge without any kind of warning. This is something we should change.

**Comment by Haaroon** [comment] 2021-02-18 11:44
thanks for replying, i agree refractoring the code for this usecase seems too costly, a warning would be a great easy fix for the time being.

**Comment by hmeyerhenke** [comment] 2021-02-19 07:32
@fabratu , this could be a task for the new student assistant.

**Comment by angriman** [comment] 2021-03-16 07:23
The multiedge warning has been merged, I am closing this.

**Closed by angriman** 2021-03-16 07:23 UTC
