### ISSUE TITLE
ttmath headers

### ISSUE THREAD

**Issue by shersoni610** [networkit/networkit#491] opened 2020-01-31 05:14 UTC
Hello

It seems make install does not copy ttmath files in the install directory. Do we need to copy
these headers manually?

**Comment by avdgrinten** [comment] 2020-01-31 07:56
That looks like a bug indeed. You can manually copy them until the issue is fixed.

**Comment by fabratu** [comment] 2020-02-17 09:06
Closing now - should be fixed in main branch.

**Closed by fabratu** 2020-02-17 09:06 UTC
