### ISSUE TITLE
TypeError: Cannot use scipy.linalg.eig for sparse A with k >= N - 1. Use scipy.linalg.eig(A.toarray()) or reduce k.

### ISSUE THREAD

**Issue by DerekChia** [networkit/networkit#796] opened 2021-08-04 09:42 UTC
Hi,

I'm getting this error `TypeError: Cannot use scipy.linalg.eig for sparse A with k >= N - 1. Use scipy.linalg.eig(A.toarray()) or reduce k.` when trying to run graph coloring. 

Code:
```
nk.coloring.SpectralColoring(g).run().getColoring()
```

Error:
```
/home/derek/anaconda3/envs/python-graph-benchmark/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py:1266: RuntimeWarning: k >= N - 1 for N * N square matrix. Attempting to use scipy.linalg.eig instead.
  warnings.warn("k >= N - 1 for N * N square matrix. "
Traceback (most recent call last):
  File "code/networkit_profile.py", line 85, in <module>
    nk.coloring.SpectralColoring(g).run().getColoring()
  File "/home/derek/anaconda3/envs/python-graph-benchmark/lib/python3.8/site-packages/networkit/coloring.py", line 49, in run
    self.prepareSpectrum()
  File "/home/derek/anaconda3/envs/python-graph-benchmark/lib/python3.8/site-packages/networkit/coloring.py", line 13, in prepareSpectrum
    spectrum = adjacencyEigenvectors(self.graph)
  File "/home/derek/anaconda3/envs/python-graph-benchmark/lib/python3.8/site-packages/networkit/algebraic.py", line 218, in adjacencyEigenvectors
    return eigenvectors(adjacencyMatrix(G), cutoff=cutoff, reverse=reverse)
  File "/home/derek/anaconda3/envs/python-graph-benchmark/lib/python3.8/site-packages/networkit/algebraic.py", line 198, in eigenvectors
    w, v = scipy.sparse.linalg.eigs(matrix, cutoff + 1, which=mode)
  File "/home/derek/anaconda3/envs/python-graph-benchmark/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1271, in eigs
    raise TypeError("Cannot use scipy.linalg.eig for sparse A with "
TypeError: Cannot use scipy.linalg.eig for sparse A with k >= N - 1. Use scipy.linalg.eig(A.toarray()) or reduce k.
```

Appreciate if anyone can give me some tips on how to solve this. Thanks.

**Comment by fabratu** [comment] 2021-08-06 07:23
The problem is in the end triggered by a bug in our code - no real actual way around it. Once a patch is merged, you can either wait for a patch-release or build NetworKit from source. 

Another (rather dirty) method would be to overwrite both `algebraic.py` and `coloring.py` from your currently installed version. Both files contain Python-code only without the need for compiling.

**Closed** 2021-08-20 06:42 UTC
