### ISSUE TITLE
DevGuide and get_started still describe scons

### ISSUE THREAD

**Issue by michitux** [networkit/networkit#249] opened 2018-10-19 08:28 UTC
While trying to find instructions what the suggested way how to build tests is, I noticed that the DevGuide (`Doc/doc/api/DevGuide.rst`) still describes scons for building tests. Further, scons is also still mentioned in `Doc/doc/get_started.rst` and used in `scripts/test.py` and `scripts/benchmark.sh`.

**Comment by avdgrinten** [comment] 2018-10-19 08:41
I removed those file just yesterday ;).

But you are right, the information on the website is outdated. The recommended way to run the test is to create your own build directory and then build with `cmake -DNETWORKIT_BUILD_TESTS=ON <path to networkit>`. You can look at `.travis.yml` for an example.

**Comment by michitux** [comment] 2018-10-19 09:40
You removed the files directly in `Doc`. However, the source files I have mentioned above still exist in the Dev branch, see e.g. https://github.com/kit-parco/networkit/blob/Dev/Doc/doc/api/DevGuide.rst

**Comment by avdgrinten** [comment] 2018-10-19 09:46
Ah, you're right. Yes, those need an update.

**Comment by avdgrinten** [comment] 2018-10-19 11:58
By the way, as detailed in #38, if someone posts a PR for `DevGuide.rst` or other `.rst` files in `Doc/`, I can easily rebuild the website using the new files.

**Comment by avdgrinten** [comment] 2019-06-12 14:04
This has already been fixed.

**Comment by michitux** [comment] 2019-11-13 12:48
`docs/DevGuide.rst` still describes scons for building the test cases.

**Comment by fabratu** [comment] 2021-02-10 10:12
Closing this because the issue is finally solved :)

**Closed by fabratu** 2021-02-10 10:12 UTC
